"""Tool 4 — Generates a premium branded discharge-summary PDF."""
from agents import function_tool
from fpdf import FPDF
from datetime import datetime
import os
import logging

logger = logging.getLogger("tools.pdf")
OUTPUT_DIR = "./generated_pdfs"
os.makedirs(OUTPUT_DIR, exist_ok=True)

# ── Brand palette (RGB) ───────────────────────────────────────────────────────
TEAL        = (13, 148, 136)
TEAL_LIGHT  = (204, 251, 241)
WHITE       = (255, 255, 255)
DARK        = (15,  23,  42)
GREY        = (100, 116, 139)
LIGHT_BG    = (248, 250, 252)
BORDER      = (226, 232, 240)
RED         = (220,  38,  38)
ORANGE      = (234,  88,  12)
GREEN       = (22,  163, 74)

RISK_COLOR  = {"low": GREEN, "moderate": ORANGE, "high": RED, "critical": RED}


# ─────────────────────────────────────────────────────────────────────────────
class NotWellPDF(FPDF):
    """fpdf2 subclass with Notwell header, footer, and helper primitives."""

    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=22)
        self._generated_at = datetime.now().strftime("%d %b %Y  %I:%M %p")

    # ── Color shortcuts ───────────────────────────────────────────────────────
    def _text(self, c):  self.set_text_color(*c)
    def _fill(self, c):  self.set_fill_color(*c)
    def _draw(self, c):  self.set_draw_color(*c)

    # ── Header ────────────────────────────────────────────────────────────────
    def header(self):
        # Teal banner
        self._fill(TEAL)
        self.rect(0, 0, self.w, 24, "F")

        self.set_y(6)
        self.set_font("Helvetica", "B", 17)
        self._text(WHITE)
        self.cell(0, 8, "  NOTWELL", align="L", ln=False)

        self.set_y(7)
        self.set_font("Helvetica", "", 9)
        self.cell(0, 7, "Discharge Summary  ", align="R", ln=True)

        # Thin accent line below banner
        self._draw(TEAL_LIGHT)
        self._fill(TEAL_LIGHT)
        self.rect(0, 24, self.w, 2, "F")

        self.set_y(30)
        self._text(DARK)

    # ── Footer ────────────────────────────────────────────────────────────────
    def footer(self):
        self.set_y(-14)
        self._draw(BORDER)
        self.line(self.l_margin, self.get_y(), self.w - self.r_margin, self.get_y())
        self.set_y(-12)
        self.set_font("Helvetica", "", 7)
        self._text(GREY)
        self.cell(
            0, 5,
            f"Generated by Notwell  ·  {self._generated_at}  ·  Confidential Medical Record",
            align="C", ln=False,
        )
        self.cell(0, 5, f"Page {self.page_no()}", align="R")

    # ── Primitives ────────────────────────────────────────────────────────────
    def section(self, title: str):
        """Teal left-bar section heading."""
        self.ln(5)
        x, y = self.get_x(), self.get_y()
        self._fill(TEAL)
        self.rect(x, y + 1, 3, 7, "F")
        self.set_x(x + 6)
        self.set_font("Helvetica", "B", 10)
        self._text(TEAL)
        self.cell(0, 9, title.upper(), ln=True)
        self._draw(BORDER)
        self.line(self.l_margin, self.get_y(), self.w - self.r_margin, self.get_y())
        self.ln(3)
        self._text(DARK)

    def kv(self, label: str, value: str, indent: float = 0):
        """Key / value row."""
        self.set_x(self.l_margin + indent)
        self.set_font("Helvetica", "B", 8)
        self._text(GREY)
        self.cell(38, 5, label.upper() + ":", ln=False)
        self.set_font("Helvetica", "", 9)
        self._text(DARK)
        self.multi_cell(0, 5, value or "N/A")

    def bullet(self, text: str, indent: float = 5):
        self.set_x(self.l_margin + indent)
        self.set_font("Helvetica", "", 9)
        self._text(DARK)
        self.cell(5, 5, "-", ln=False)
        self.multi_cell(0, 5, str(text))

    def table_header(self, cols: list, widths: list, row_h: float = 6):
        self._fill(TEAL)
        self._text(WHITE)
        self.set_font("Helvetica", "B", 8)
        for w, label in zip(widths, cols):
            self.cell(w, row_h, label, border=0, fill=True, align="C")
        self.ln()
        self._text(DARK)

    def table_row(self, cells: list, widths: list, row_i: int, row_h: float = 5):
        fill = row_i % 2 == 0
        if fill:
            self._fill(LIGHT_BG)
        self.set_font("Helvetica", "", 8)
        self._text(DARK)
        for w, val in zip(widths, cells):
            self.cell(w, row_h, str(val)[:30], border=0, fill=fill, align="C")
        self.ln()


# ─────────────────────────────────────────────────────────────────────────────
def build_discharge_pdf(
    patient_name: str,
    session_id: str,
    patient_id: str = "",
    consultant_name: str = "",
    # SOAP
    subjective: str = "",
    objective: str = "",
    assessment: str = "",
    plan_soap: str = "",
    icd10_codes: list = None,
    # Summary
    chief_complaint: str = "",
    diagnosis_summary: str = "",
    key_findings: list = None,
    risk_level: str = "low",
    # Treatment
    treatment_steps: list = None,
    prescribed_medications: list = None,
    discharge_instructions: str = "",
    precautions: list = None,
    # Follow-up
    followup_items: list = None,
    followup_notes: str = "",
    # Patient history
    known_conditions: list = None,
    allergies: list = None,
    # Legacy passthrough (used when called from old API code)
    diagnosis_summary_text: str = "",
    treatment_plan_text: str = "",
    followup_text: str = "",
) -> str:
    """Build a premium branded discharge summary PDF. Returns the saved file path."""

    icd10_codes           = icd10_codes or []
    key_findings          = key_findings or []
    treatment_steps       = treatment_steps or []
    prescribed_medications = prescribed_medications or []
    precautions           = precautions or []
    followup_items        = followup_items or []
    known_conditions      = known_conditions or []
    allergies             = allergies or []

    pdf = NotWellPDF()
    pdf.add_page()
    today = datetime.now().strftime("%d %B %Y")

    # ── Patient Info Card ────────────────────────────────────────────────────
    card_w = pdf.w - pdf.l_margin - pdf.r_margin
    card_h = 26
    cx, cy = pdf.l_margin, pdf.get_y()
    pdf._fill(LIGHT_BG)
    pdf._draw(BORDER)
    pdf.rect(cx, cy, card_w, card_h, "FD")

    half = card_w / 2

    pdf.set_xy(cx + 4, cy + 4)
    pdf.set_font("Helvetica", "B", 11)
    pdf._text(DARK)
    pdf.cell(half, 6, patient_name, ln=False)

    pdf.set_font("Helvetica", "", 8)
    pdf._text(GREY)
    pdf.cell(half - 4, 6, f"Date: {today}", align="R", ln=True)

    pdf.set_x(cx + 4)
    pdf.set_font("Helvetica", "", 8)
    pdf._text(GREY)
    pdf.cell(half, 5, f"Patient ID: {patient_id or 'N/A'}", ln=False)
    pdf.cell(half - 4, 5, f"Session: {session_id[:16]}", align="R", ln=True)

    pdf.set_x(cx + 4)
    pdf.cell(half, 5, f"Consultant: {consultant_name or 'N/A'}", ln=False)

    # Risk badge
    risk_col = RISK_COLOR.get(str(risk_level).lower(), GREY)
    pdf._fill(risk_col)
    pdf._text(WHITE)
    pdf.set_font("Helvetica", "B", 8)
    badge = f"  RISK: {str(risk_level).upper()}  "
    pdf.cell(half - 4, 5, badge, align="R", fill=True, ln=True)

    pdf.set_y(cy + card_h + 4)
    pdf._text(DARK)

    # ── Chief Complaint ──────────────────────────────────────────────────────
    if chief_complaint:
        pdf.section("Chief Complaint")
        pdf.set_font("Helvetica", "I", 10)
        pdf.multi_cell(0, 6, f'"{chief_complaint}"')
        pdf.ln(1)

    # ── SOAP Clinical Note ───────────────────────────────────────────────────
    if any([subjective, objective, assessment, plan_soap]):
        pdf.section("SOAP Clinical Note")
        for lbl, val in [
            ("S — Subjective", subjective),
            ("O — Objective",  objective),
            ("A — Assessment", assessment),
            ("P — Plan",       plan_soap),
        ]:
            if val:
                pdf.kv(lbl, val)
                pdf.ln(1)

    # ── ICD-10 Codes ─────────────────────────────────────────────────────────
    if icd10_codes:
        pdf.section("ICD-10 Diagnosis Codes")
        for code in icd10_codes:
            pdf.bullet(str(code))

    # ── Diagnosis Summary ────────────────────────────────────────────────────
    pdf.section("Diagnosis Summary")
    pdf.set_font("Helvetica", "", 9)
    pdf.multi_cell(0, 5, diagnosis_summary or diagnosis_summary_text or "N/A")
    if key_findings:
        pdf.ln(2)
        pdf.set_font("Helvetica", "B", 8)
        pdf._text(GREY)
        pdf.cell(0, 5, "KEY FINDINGS:", ln=True)
        for f in key_findings:
            pdf.bullet(str(f))
        pdf._text(DARK)

    # ── Patient History ──────────────────────────────────────────────────────
    if known_conditions or allergies:
        pdf.section("Patient History")
        if known_conditions:
            pdf.set_font("Helvetica", "B", 8)
            pdf._text(GREY)
            pdf.cell(0, 5, "KNOWN CONDITIONS:", ln=True)
            for c in known_conditions:
                pdf.bullet(str(c))
        if allergies:
            pdf.ln(2)
            pdf.set_font("Helvetica", "B", 8)
            pdf._text(GREY)
            pdf.cell(0, 5, "ALLERGIES:", ln=True)
            for a in allergies:
                if isinstance(a, dict):
                    line = a.get("substance", "Unknown")
                    if a.get("reaction"):
                        line += f" — {a['reaction']}"
                    if a.get("severity"):
                        line += f" ({a['severity']})"
                else:
                    line = str(a)
                pdf.bullet(line)
        pdf._text(DARK)

    # ── Treatment Plan ───────────────────────────────────────────────────────
    pdf.section("Treatment Plan")

    if treatment_steps:
        for i, step in enumerate(treatment_steps, 1):
            action    = step.get("action", str(step))    if isinstance(step, dict) else str(step)
            rationale = step.get("rationale", "")        if isinstance(step, dict) else ""
            timeframe = step.get("timeframe", "")        if isinstance(step, dict) else ""
            pdf.set_x(pdf.l_margin + 3)
            pdf.set_font("Helvetica", "B", 9)
            pdf._text(TEAL)
            pdf.cell(7, 5, f"{i}.", ln=False)
            pdf._text(DARK)
            pdf.set_font("Helvetica", "", 9)
            pdf.multi_cell(0, 5, action)
            if rationale:
                pdf.set_x(pdf.l_margin + 10)
                pdf.set_font("Helvetica", "I", 8)
                pdf._text(GREY)
                pdf.multi_cell(0, 4, f"Rationale: {rationale}")
            if timeframe:
                pdf.set_x(pdf.l_margin + 10)
                pdf.set_font("Helvetica", "I", 8)
                pdf._text(TEAL)
                pdf.multi_cell(0, 4, f"Timeframe: {timeframe}")
            pdf._text(DARK)
            pdf.ln(1)

    # Medications table
    if prescribed_medications:
        pdf.ln(2)
        pdf.set_font("Helvetica", "B", 8)
        pdf._text(GREY)
        pdf.cell(0, 5, "PRESCRIBED MEDICATIONS:", ln=True)
        pdf.table_header(["Medication", "Dosage", "Frequency", "Active"], [65, 40, 45, 22])
        for i, med in enumerate(prescribed_medications):
            name   = med.get("name", str(med))       if isinstance(med, dict) else str(med)
            dosage = med.get("dosage", "-")      if isinstance(med, dict) else "-"
            freq   = med.get("frequency", "-")   if isinstance(med, dict) else "-"
            active = "Yes" if (med.get("active", True) if isinstance(med, dict) else True) else "No"
            pdf.table_row([name, dosage or "-", freq or "-", active], [65, 40, 45, 22], i)
        pdf._text(DARK)
        pdf.ln(1)

    # Discharge instructions
    disinstr = discharge_instructions or treatment_plan_text
    if disinstr:
        pdf.ln(2)
        pdf.set_font("Helvetica", "B", 8)
        pdf._text(GREY)
        pdf.cell(0, 5, "DISCHARGE INSTRUCTIONS:", ln=True)
        pdf.set_font("Helvetica", "", 9)
        pdf._text(DARK)
        pdf.multi_cell(0, 5, disinstr)

    if precautions:
        pdf.ln(2)
        pdf.set_font("Helvetica", "B", 8)
        pdf._text(GREY)
        pdf.cell(0, 5, "PRECAUTIONS:", ln=True)
        for p in precautions:
            pdf.bullet(str(p))
        pdf._text(DARK)

    # ── Follow-up Plan ───────────────────────────────────────────────────────
    pdf.section("Follow-up Plan")
    if followup_items:
        fw = [72, 38, 40, 22]
        pdf.table_header(["Reason", "Date", "Department", "Priority"], fw)
        for i, fu in enumerate(followup_items):
            reason   = fu.get("reason", str(fu))        if isinstance(fu, dict) else str(fu)
            date     = fu.get("suggested_date", "-") if isinstance(fu, dict) else "-"
            dept     = fu.get("department", "-")   if isinstance(fu, dict) else "-"
            priority = fu.get("priority", "low")        if isinstance(fu, dict) else "low"
            fill     = i % 2 == 0
            if fill:
                pdf._fill(LIGHT_BG)
            pri_col = RISK_COLOR.get(str(priority).lower(), GREY)
            pdf.set_font("Helvetica", "", 8)
            pdf._text(DARK)
            pdf.cell(fw[0], 5, reason[:40],       border=0, fill=fill)
            pdf.cell(fw[1], 5, str(date)[:18],    border=0, fill=fill, align="C")
            pdf.cell(fw[2], 5, str(dept)[:18],    border=0, fill=fill, align="C")
            pdf._text(pri_col)
            pdf.cell(fw[3], 5, str(priority).upper(), border=0, fill=fill, align="C")
            pdf._text(DARK)
            pdf.ln()
    else:
        pdf.set_font("Helvetica", "I", 9)
        pdf._text(GREY)
        pdf.cell(0, 5, followup_text or "No follow-ups scheduled.", ln=True)
        pdf._text(DARK)

    if followup_notes:
        pdf.ln(1)
        pdf.set_font("Helvetica", "I", 8)
        pdf._text(GREY)
        pdf.multi_cell(0, 4, f"Notes: {followup_notes}")
        pdf._text(DARK)

    # ── Clinician Sign-off ───────────────────────────────────────────────────
    pdf.section("Clinician Sign-off")
    pdf.ln(2)
    pdf.set_font("Helvetica", "", 9)
    pdf._text(GREY)
    pdf.cell(50, 5, "Approved by:", ln=False)
    pdf._text(DARK)
    pdf.cell(0, 5, consultant_name or "", ln=True)
    pdf.ln(6)
    sig_x = pdf.l_margin
    sig_y = pdf.get_y()
    pdf._draw(DARK)
    pdf.line(sig_x, sig_y, sig_x + 72, sig_y)
    pdf.line(sig_x + 90, sig_y, sig_x + 162, sig_y)
    pdf.ln(2)
    pdf.set_font("Helvetica", "", 7)
    pdf._text(GREY)
    pdf.cell(80, 4, "Signature")
    pdf.cell(0, 4, f"Date: {today}", ln=True)

    # ── Save ─────────────────────────────────────────────────────────────────
    path = os.path.join(OUTPUT_DIR, f"discharge_{session_id}.pdf")
    pdf.output(path)
    logger.info(f"PDF generated: {path}")
    return path


# ─────────────────────────────────────────────────────────────────────────────
@function_tool
def generate_discharge_pdf(
    patient_name: str,
    diagnosis_summary: str,
    treatment_plan_text: str,
    followup_text: str,
    session_id: str,
    patient_id: str = "",
    consultant_name: str = "",
) -> str:
    """Generate a discharge-summary PDF and return its file path.

    Args:
        patient_name: Full name of the patient.
        diagnosis_summary: Condensed diagnosis/summary text.
        treatment_plan_text: Treatment plan and discharge instructions.
        followup_text: Follow-up recommendations.
        session_id: Pipeline session id, used to name the file.
        patient_id: The patient's unique identifier.
        consultant_name: Name of the reviewing/approving clinician.
    """
    try:
        return build_discharge_pdf(
            patient_name=patient_name,
            session_id=session_id,
            patient_id=patient_id,
            consultant_name=consultant_name,
            diagnosis_summary_text=diagnosis_summary,
            treatment_plan_text=treatment_plan_text,
            followup_text=followup_text,
        )
    except Exception as e:
        logger.error(f"generate_discharge_pdf failed: {e}")
        return f"Error generating PDF: {e}"
